# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - run: mvn -B test --file pom.xml
    - run: mkdir staging && cp target/*.war staging
    - uses: actions/upload-artifact@v1
      with:
        name: Package
        path: staging
    - name: Setup sonarqube
      uses: warchant/setup-sonar-scanner@v1
    - name: Run sonarqube
      env:
       # to get access to secrets.SONAR_TOKEN, provide GITHUB_TOKEN
       GITHUB_TOKEN: 9021b1208eda164e342460a4c9059c61e6fc10ec
      run: mvn sonar:sonar 
         -Dsonar.login=6edc2d3c60eb8b19e9aec5681db376b6707e7665
         -Dsonar.host.url=http://18.223.76.84:9000 
         -Dsonar.projectKey=ecommerce 
         -Dsonar.exclusions=**/*.java,**/*.jar
    - uses: HurricanKai/Publish-Docker-Github-Action@master
      with:
       name: madhu216/ecommerce
       username: madhu216
       password: madhu216@216
       dockerfile: Dockerfile
    - name: tomcat deploy
      run: curl -v -u tomcat:tomcat -T /home/runner/work/ecommerce/ecommerce/target/ecommerce.war 'http://ec2-3-136-22-140.us-east-2.compute.amazonaws.com:8080//manager/text/deploy?path=/ecommerce.war'
    - name: MS Teams Action
      uses: FTsbrown/msteams-action@v1.0.1
      with:
        # Title of the message
        TITLE: Team Notifications
        # Body of the message
        BODY: Build status
        # If set, A MS Teams notification will be sent to this webhook
        MS_TEAMS_WEBHOOK: https://outlook.office.com/webhook/1880ec80-4a8d-4b3a-acdd-210b0c825748@44e65903-6f89-4a2d-a7dd-a3542dc38775/JenkinsCI/2ec2fda47af345dfb51258749a8044e3/79fd4a4a-b56a-4090-ac7a-57088e1367dd
   


      
    
